import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import argparse

def read_frames_file(filename, vendor="altera"):
    """
    Read the capture file and extract the data table.
    Returns a pandas DataFrame with the signal data.
    """
    if vendor == "nv":
        # NV CSV format generated by ila.py write_csv:
        # Header: Sample, ptp_sif_nsec, ptp_sif_sec, ptp_sync_nsec, ptp_sync_sec, frame_cnt, sof, eof, ...
        csv_df = pd.read_csv(filename)

        # Ensure required columns exist
        required_cols = ['Sample', 'ptp_sif_nsec', 'ptp_sif_sec', 'ptp_sync_nsec', 'ptp_sync_sec', 'frame_cnt']
        for c in required_cols:
            if c not in csv_df.columns:
                raise ValueError(f"Missing expected column in CSV: {c}")

        def parse_auto(val):
            if isinstance(val, (int, np.integer)):
                return int(val)
            if isinstance(val, str):
                v = val.strip()
                try:
                    if v.startswith(("0x","0X")):
                        return int(v, 16)
                    if v.startswith(("0b","0B")):
                        return int(v, 2)
                    return int(v, 10)
                except Exception:
                    # Fallback: try hex without 0x
                    try:
                        return int(v, 16)
                    except Exception:
                        return 0
            # Unknown type
            return 0

        samples = csv_df['Sample'].astype(int).rename('sample')

        # Map NV fields to common schema: '1','2' (current), '8','9' (packet)
        secs_current = csv_df['ptp_sync_sec'].map(parse_auto).astype('int64').rename('1')
        nanos_current = csv_df['ptp_sync_nsec'].map(parse_auto).astype('int64').rename('2')
        secs_packet = csv_df['ptp_sif_sec'].map(parse_auto).astype('int64').rename('8')
        nanos_packet = csv_df['ptp_sif_nsec'].map(parse_auto).astype('int64').rename('9')

        # Optional fields
        cols = [samples, secs_current, nanos_current, secs_packet, nanos_packet]
        frame_cnt = csv_df['frame_cnt'].map(parse_auto).astype(int).rename('frame_cnt')
        cols.append(frame_cnt)
        if 'sof' in csv_df.columns:
            cols.append(csv_df['sof'].map(parse_auto).astype(int).rename('sof'))
        if 'eof' in csv_df.columns:
            cols.append(csv_df['eof'].map(parse_auto).astype(int).rename('eof'))

        df = pd.concat(cols, axis=1)
        df = df[1024:2048]
        # df = df[5:14000]
        # df = df[:16380]
        return df
    if vendor == "xilinx":
        # Xilinx CSV format: header on line 1, radix on line 2, then data rows
        # We skip the second line and parse hex fields.
        csv_df = pd.read_csv(filename, skiprows=[1])

        # Standardize column names we need
        # Required columns in the CSV
        required_cols = [
            'Sample in Buffer',
            'u_hololink_top/prb_dst_data[79:0]',
            'u_hololink_top/prb_dst_valid',
            'u_hololink_top/ptp_ts[79:0]',
            'u_hololink_top/ptp_ts_en',
            'u_hololink_top/frame_cnt[11:0]'
        ]
        for c in required_cols:
            if c not in csv_df.columns:
                raise ValueError(f"Missing expected column in CSV: {c}")

        # Helper to parse 80-bit PTP time: [secs | nanos32]
        # Returns (seconds, nanoseconds) where low 32 bits are already nanoseconds
        def parse_80bit_ts(hex_str):
            if isinstance(hex_str, str):
                hex_str = hex_str.strip()
            # Some CSV exporters might drop leading zeros; int(x,16) handles that
            try:
                value = int(hex_str, 16)
            except Exception:
                return 0, 0
            secs = value >> 32
            nanos = value & 0xFFFFFFFF
            return int(secs), int(nanos)

        # Build output DataFrame with columns similar to Altera parser
        samples = csv_df['Sample in Buffer'].astype(int).rename('sample')

        # Parse base fields (we will assign roles after gating)
        ptp_hex = csv_df['u_hololink_top/ptp_ts[79:0]'].astype(str)
        ptp_secs, ptp_nanos = zip(*ptp_hex.map(parse_80bit_ts))
        ptp_secs = pd.Series(ptp_secs).astype('int64')
        ptp_nanos = pd.Series(ptp_nanos).astype('int64')

        prb_hex = csv_df['u_hololink_top/prb_dst_data[79:0]'].astype(str)
        prb_secs, prb_nanos = zip(*prb_hex.map(parse_80bit_ts))
        prb_secs = pd.Series(prb_secs).astype('int64')
        prb_nanos = pd.Series(prb_nanos).astype('int64')

        # Zero out when valid/en flags are not asserted to mimic previous valid mask behavior
        ptp_en = csv_df['u_hololink_top/ptp_ts_en'].astype(int)
        prb_valid = csv_df['u_hololink_top/prb_dst_valid'].astype(int)
        sof = csv_df['u_hololink_top/sof'].astype(int) if 'u_hololink_top/sof' in csv_df.columns else None

        # For Xilinx capture, treat PRB data as the current time and PTP as the packet time
        # Do not mask the current time so the first sample is included; mask packet by ptp_en
        secs_current = prb_secs.rename('1')
        nanos_current = prb_nanos.rename('2')
        secs_packet = pd.Series(ptp_secs, name='8').where(ptp_en == 1, other=0).astype('int64')
        nanos_packet = pd.Series(ptp_nanos, name='9').where(ptp_en == 1, other=0).astype('int64')

        # Frame count for monotonicity analysis
        frame_cnt_hex = csv_df['u_hololink_top/frame_cnt[11:0]'].astype(str)
        frame_cnt = frame_cnt_hex.apply(lambda x: int(x, 16) if isinstance(x, str) else int(x))
        frame_cnt = frame_cnt.rename('frame_cnt').astype(int)

        # Compose final DataFrame
        df = pd.concat([
            samples,
            secs_current,
            nanos_current,
            secs_packet,
            nanos_packet,
            frame_cnt
        ], axis=1)
        return df
    else:
        with open(filename, 'r') as f:
            lines = f.readlines()
        
        # Find the start of the data table
        data_start = None
        for i, line in enumerate(lines):
            if line.strip().startswith('sample'):
                data_start = i + 1
                break
        
        if data_start is None:
            raise ValueError("Could not find data table in file")
        
        # Extract data lines
        data_lines = []
        for line in lines[data_start:]:
            line = line.strip()
            if line and not line.startswith('Signals->'):
                # Split the line into columns
                parts = line.split()
                if len(parts) >= 10:  # We need at least 10 columns (0-9)
                    if all(x == "0" for x in parts[1:]):
                        data_start += 1
                    else:
                        data_lines.append(parts)
                else:
                    print(f"Skipped {line}")
        
        # Determine number of columns dynamically
        num_columns = len(data_lines[0]) if data_lines else 11
        column_names = ['sample'] + [str(i) for i in range(num_columns - 1)]
        
        # Create DataFrame
        df = pd.DataFrame(data_lines, columns=column_names)
        
        # Convert to appropriate data types
        df['sample'] = df['sample'].astype(int)
        # Convert all signal columns to int
        for col in column_names[1:]:  # Skip 'sample' column
            df[col] = df[col].astype(int)
        
        return df

def calculate_time_difference(df):
    """
    Calculate the time difference between packet time and current time.
    Returns the difference in nanoseconds.
    """
    # Convert to full nanosecond timestamps using 64-bit integer math to avoid float quantization
    seconds_current = df['1'].astype('int64')
    nanos_current = df['2'].astype('int64')
    seconds_packet = df['8'].astype('int64')
    nanos_packet = df['9'].astype('int64')

    current_time_ns = seconds_current * np.int64(1_000_000_000) + nanos_current
    packet_time_ns = seconds_packet * np.int64(1_000_000_000) + nanos_packet

    # Calculate difference (current_time - packet_time)
    time_diff_ns = current_time_ns - packet_time_ns

    return time_diff_ns

def analyze_frame_count(df):
    """
    Analyze frame count to check if it's monotonically increasing.
    Frame count is assumed to be in the next-to-last column.
    """
    # Prefer named 'frame_cnt' if present; otherwise fallback to next-to-last
    columns = df.columns.tolist()
    if 'frame_cnt' in df.columns:
        frame_count_col = 'frame_cnt'
    else:
        if len(columns) < 2:
            raise ValueError("Not enough columns to find frame count")
        frame_count_col = columns[-2]  # Second to last column
    
    print(f"Analyzing frame count in column: '{frame_count_col}'")
    
    # Get frame count values
    frame_counts = df[frame_count_col].values
    
    # Check for exact increment by 1, accounting for 12-bit rollover (4095 -> 0)
    diffs = np.diff(frame_counts)
    
    # Handle rollover: 4095 -> 0 should be considered as +1
    rollover_mask = (frame_counts[:-1] == 4095) & (frame_counts[1:] == 0)
    diffs[rollover_mask] = 1
    
    is_monotonic = np.all(diffs == 1)
    
    # Find any non-perfect increments
    not_monotonic = np.where(diffs != 1)[0]
    
    # Calculate statistics
    frame_stats = {
        'column_name': frame_count_col,
        'total_frames': len(frame_counts),
        'is_monotonic': is_monotonic,
        'min_frame_count': np.min(frame_counts),
        'max_frame_count': np.max(frame_counts),
        'frame_count_range': np.max(frame_counts) - np.min(frame_counts),
        'num_decreases': len(not_monotonic),
        'decrease_indices': not_monotonic,
        'first_frame_count': frame_counts[0],
        'last_frame_count': frame_counts[-1]
    }
    
    return frame_stats

def analyze_latency(df, time_diff_ns):
    """
    Perform statistical analysis on the latency data.
    """
    # Filter out samples where timestamps are invalid (any component is zero)
    valid_mask = (df['1'] != 0) & (df['2'] != 0) & (df['8'] != 0) & (df['9'] != 0)
    valid_data = df[valid_mask]
    valid_time_diff = time_diff_ns[valid_mask]
    
    # Store the first valid data point for reporting (but don't include in calculations)
    first_data_point_ns = valid_time_diff.iloc[0] if len(valid_time_diff) > 0 else 0
    
    # Remove the first valid data point as an outlier
    if len(valid_time_diff) > 3:
        valid_data = valid_data.iloc[3:]  # Skip first row
        valid_time_diff = valid_time_diff[3:]  # Skip first element
    
    if len(valid_time_diff) == 0:
        stats = {
            'total_samples': len(df),
            'valid_samples': 0,
            'first_data_point_ns': 0,
            'mean_latency_ns': np.nan,
            'std_latency_ns': np.nan,
            'min_latency_ns': np.nan,
            'max_latency_ns': np.nan,
            'median_latency_ns': np.nan,
            'p95_latency_ns': np.nan,
            'p99_latency_ns': np.nan
        }
        return stats, valid_time_diff

    stats = {
        'total_samples': len(df),
        'valid_samples': len(valid_data),
        'first_data_point_ns': first_data_point_ns,
        'mean_latency_ns': np.mean(valid_time_diff),
        'std_latency_ns': np.std(valid_time_diff),
        'min_latency_ns': np.min(valid_time_diff),
        'max_latency_ns': np.max(valid_time_diff),
        'median_latency_ns': np.median(valid_time_diff),
        'p95_latency_ns': np.percentile(valid_time_diff, 95),
        'p99_latency_ns': np.percentile(valid_time_diff, 99)
    }
    
    return stats, valid_time_diff

def plot_latency_analysis(df, time_diff_ns, valid_time_diff, stats):
    """
    Create comprehensive plots of the latency analysis.
    """
    fig, axes = plt.subplots(1, 2, figsize=(15, 6))
    fig.suptitle('Latency Analysis: Packet Time vs Current Time', fontsize=16)
    
    # Align samples with filtered valid_time_diff (already excludes first 3)
    valid_samples = df.loc[valid_time_diff.index, 'sample']
    
    # Plot 1: Latency over time (only valid samples, excluding first)
    if len(valid_time_diff) > 0:
        axes[0].plot(valid_samples, valid_time_diff / 1e3, 'b-', alpha=0.7, linewidth=0.5)
    else:
        axes[0].text(0.5, 0.5, 'No valid samples', ha='center', va='center', transform=axes[0].transAxes)
    axes[0].set_xlabel('Sample Number')
    axes[0].set_ylabel('Latency (μs)')
    axes[0].set_title('Latency Over Time (Valid Samples Only, excluding first)')
    axes[0].grid(True, alpha=0.3)
    
    # Plot 2: Histogram of valid latency values
    hist_counts = None
    hist_bins = None
    if len(valid_time_diff) > 0:
        hist_counts, hist_bins, _ = axes[1].hist(valid_time_diff / 1e3, bins=50, alpha=0.7, color='green', edgecolor='black')
        axes[1].axvline(stats['mean_latency_ns'] / 1e3, color='red', linestyle='--', 
                       label=f'Mean: {stats["mean_latency_ns"]/1e3:.2f} μs')
        axes[1].axvline(stats['median_latency_ns'] / 1e3, color='orange', linestyle='--', 
                       label=f'Median: {stats["median_latency_ns"]/1e3:.2f} μs')
        axes[1].legend()
    else:
        axes[1].text(0.5, 0.5, 'No valid samples', ha='center', va='center', transform=axes[1].transAxes)
    axes[1].set_xlabel('Latency (μs)')
    axes[1].set_ylabel('Frequency')
    axes[1].set_title('Latency Distribution (Valid Samples Only, excluding first)')
    axes[1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    return fig, hist_counts, hist_bins


def get_frame_count_status(frame_stats):
    """
    Get a simple pass/fail status for frame count monotonicity.
    Returns a string with the status and any failure details.
    """
    if frame_stats['is_monotonic']:
        return "PASS - Frame count increments by exactly 1"
    else:
        status = "FAIL - Frame count does not increment by exactly 1"
        details = []
        
        if frame_stats['num_decreases'] > 0:
            first_decrease_idx = frame_stats['decrease_indices'][0]
            details.append(f"First non-perfect increment at sample {first_decrease_idx}")
        
        if details:
            status += f" ({'; '.join(details)})"
        
        return status

def print_statistics(stats, frame_count_status):
    """
    Print detailed statistics about the latency analysis.
    """
    print("=" * 60)
    print("LATENCY ANALYSIS RESULTS")
    print("=" * 60)
    print(f"Total Samples: {stats['total_samples']:,}")
    print(f"Valid Samples: {stats['valid_samples']:,}")
    valid_pct = (stats['valid_samples']/stats['total_samples']*100) if stats['total_samples'] > 0 else 0
    print(f"Valid Percentage: {valid_pct:.1f}%")
    print()
    print("FRAME COUNT STATUS:")
    print("-" * 50)
    print(frame_count_status)
    print()
    print("FIRST DATA POINT (Excluded from calculations):")
    print("-" * 50)
    print(f"First Data Point: {stats['first_data_point_ns']/1e3:8.3f} μs")
    print()
    print("LATENCY STATISTICS (Valid Samples Only, excluding first):")
    print("-" * 50)
    if stats['valid_samples'] > 0:
        print(f"Mean Latency:     {stats['mean_latency_ns']/1e3:8.3f} μs")
        print(f"Median Latency:   {stats['median_latency_ns']/1e3:8.3f} μs")
        print(f"Std Deviation:    {stats['std_latency_ns']/1e3:8.3f} μs")
        print(f"Min Latency:      {stats['min_latency_ns']/1e3:8.3f} μs")
        print(f"Max Latency:      {stats['max_latency_ns']/1e3:8.3f} μs")
        print(f"95th Percentile:  {stats['p95_latency_ns']/1e3:8.3f} μs")
        print(f"99th Percentile:  {stats['p99_latency_ns']/1e3:8.3f} μs")
    else:
        print("No valid samples to compute statistics.")
    print("=" * 60)

def main():
    """
    Main function to run the latency analysis.
    """
    parser = argparse.ArgumentParser(description='Latency analysis from captured traces')
    parser.add_argument('--file', '-f', default='output/samples.csv', help='Input capture file path')
    parser.add_argument('--vendor', '-v', default='nv', choices=['altera', 'xilinx', 'nv'], help='Capture format/vendor')
    args = parser.parse_args()
    filename = args.file
    vendor = args.vendor
    
    print(f"Reading frames data (vendor={vendor})...")
    df = read_frames_file(filename, vendor=vendor)
    print(f"Loaded {len(df)} samples")
    
    print("Analyzing frame count...")
    frame_stats = analyze_frame_count(df)
    frame_count_status = get_frame_count_status(frame_stats)
    
    print("Calculating time differences...")
    time_diff_ns = calculate_time_difference(df)
    
    print("Analyzing latency...")
    stats, valid_time_diff = analyze_latency(df, time_diff_ns)
    
    print_statistics(stats, frame_count_status)
    
    print("Creating plots...")
    fig, hist_counts, hist_bins = plot_latency_analysis(df, time_diff_ns, valid_time_diff, stats)

    # Export CSVs of plotted data if valid samples exist
    if len(valid_time_diff) > 0:
        # Time-series CSV: sample vs latency (microseconds)
        valid_samples = df.loc[valid_time_diff.index, 'sample']
        ts_df = pd.DataFrame({
            'sample': valid_samples.values,
            'latency_us': (valid_time_diff.values / 1e3)
        })
        ts_df.to_csv('output/latency_time_series.csv', index=False)

        # Histogram CSV: each bin range with count
        if hist_counts is not None and hist_bins is not None:
            hist_df = pd.DataFrame({
                'bin_left_us': hist_bins[:-1],
                'bin_right_us': hist_bins[1:],
                'count': hist_counts.astype(int)
            })
            hist_df.to_csv('output/latency_histogram.csv', index=False)
        print("CSV files saved as 'output/latency_time_series.csv' and 'output/latency_histogram.csv'")
    else:
        print("No valid samples; skipping CSV export.")
    
    # Save the plot
    fig.savefig('output/latency_analysis.png', dpi=300, bbox_inches='tight')
    print("Plot saved as 'output/latency_analysis.png'")

    # Additional P99 (exclude worst 1%) graphs and CSVs
    if len(valid_time_diff) > 0:
        p99_threshold = np.percentile(valid_time_diff, 99)
        p99_mask = valid_time_diff <= p99_threshold
        p99_time_diff = valid_time_diff[p99_mask]
        p99_samples = df.loc[p99_time_diff.index, 'sample']

        # Time series (P99)
        plt.figure(figsize=(10, 4))
        if len(p99_time_diff) > 0:
            plt.plot(p99_samples, p99_time_diff / 1e3, 'b-', alpha=0.7, linewidth=0.5)
        else:
            plt.text(0.5, 0.5, 'No valid samples after P99 filter', ha='center', va='center', transform=plt.gca().transAxes)
        plt.xlabel('Sample Number')
        plt.ylabel('Latency (μs)')
        plt.title('Latency Over Time (Excluding Worst 1%)')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig('output/latency_time_series_p99.png', dpi=300, bbox_inches='tight')
        plt.close()

        # Histogram (P99)
        plt.figure(figsize=(10, 4))
        if len(p99_time_diff) > 0:
            hc, hb, _ = plt.hist(p99_time_diff / 1e3, bins=50, alpha=0.7, color='green', edgecolor='black')
            plt.axvline(np.mean(p99_time_diff) / 1e3, color='red', linestyle='--', label=f"Mean: {np.mean(p99_time_diff)/1e3:.2f} μs")
            plt.axvline(np.median(p99_time_diff) / 1e3, color='orange', linestyle='--', label=f"Median: {np.median(p99_time_diff)/1e3:.2f} μs")
            plt.legend()
        else:
            hc, hb = None, None
            plt.text(0.5, 0.5, 'No valid samples after P99 filter', ha='center', va='center', transform=plt.gca().transAxes)
        plt.xlabel('Latency (μs)')
        plt.ylabel('Frequency')
        plt.title('Latency Distribution (Excluding Worst 1%)')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig('output/latency_histogram_p99.png', dpi=300, bbox_inches='tight')
        plt.close()

        # P99 CSV exports
        # Time-series CSV (P99)
        ts_p99_df = pd.DataFrame({
            'sample': p99_samples.values,
            'latency_us': (p99_time_diff.values / 1e3)
        })
        ts_p99_df.to_csv('output/latency_time_series_p99.csv', index=False)

        # Histogram CSV (P99)
        if hc is not None and hb is not None:
            hist_p99_df = pd.DataFrame({
                'bin_left_us': hb[:-1],
                'bin_right_us': hb[1:],
                'count': hc.astype(int)
            })
            hist_p99_df.to_csv('output/latency_histogram_p99.csv', index=False)
        print("P99 plots saved as 'output/latency_time_series_p99.png' and 'output/latency_histogram_p99.png'")
        print("P99 CSV files saved as 'output/latency_time_series_p99.csv' and 'output/latency_histogram_p99.csv'")

    # Show the plot
    plt.show()
    
    return df, time_diff_ns, stats, frame_stats

if __name__ == "__main__":
    df, time_diff_ns, stats, frame_stats = main()
